// import fs from 'fs-extra';
import path from 'path';
import dedent from 'dedent';
import { createTypegingForBuilders, generateTypedApiFromPath } from '..';
import { compile, expression } from '../..';

describe('Codegen', () => {
    it('should throw when file doesnt exist', async () => {
      const inOutConfig = {
        input: path.resolve(__dirname, './ljdskfhlkjshdfkjasdf'),
      };

      await expect(generateTypedApiFromPath.bind(null, inOutConfig)).rejects.toThrow();
    })

    it('should emit file when file doesnt exist', async () => {
      const inOutConfig = {
        input: path.resolve(__dirname, './example/fixtures'),
      };

      await generateTypedApiFromPath(inOutConfig);
      
    })


    it('should generate typings', async () => {
      const inOutConfig = {
        input: path.resolve(__dirname, './example/fixtures'),
      };

      class Type1 {};

      const compiled = compile(
        expression(
          ({ the }) => the(Boolean).and.check(Boolean),
          (isAlive: Boolean, isWell: Boolean) => 'First',
        ),

        expression(
          ({ the }) => the(String).and.writes(String),
          (isAlive: string, isWell: string) => 'First',
        ),

        expression(
          ({ the }) => the(Type1).and.type(Boolean),
          (isAlive: Type1, isWell: boolean) => 'First',
        ),
      
        expression(
          ({ the }) => the(Boolean).and.well(String),
          ({ the }) => the(Boolean).and.very.well(String),
          (isAlive: Boolean, isWell: Boolean) => 'Second',
        )
      );

      const typings = await createTypegingForBuilders(inOutConfig, compiled);
      expect(typings).toEqual(dedent`
        /* ------------------------------------
        *  Generated by chai-latte
        *  Please do not edit this file directly
        *  Instead, edit the file './fixtures'
        * ------------------------------------
        */

        import builder from './fixtures';

        type Expressions = typeof builder.__expressions;
        type ExpressionCallback<Idx extends number> = Expressions[Idx][0]['callback'];
        type Arg<Idx extends number, ArgIndex extends number> = Parameters<ExpressionCallback<Idx>>[ArgIndex];
        type Return<Idx extends number> = ReturnType<ExpressionCallback<Idx>>;

        type Root = {
          the: {
            (bool: Arg<0, 0>) : {
              and: {
                check: {
                  (bool: Arg<0, 1>) : Return<0>;
                };
                well: {
                  (str: Arg<3, 1>) : Return<3>;
                };
                very: {
                  well: {
                    (str: Arg<3, 1>) : Return<3>;
                  };
                };
              };
            };
            (str: Arg<1, 0>) : {
              and: {
                writes: {
                  (str: Arg<1, 1>) : Return<1>;
                };
              };
            };
            (type1: Arg<2, 0>) : {
              and: {
                type: {
                  (bool: Arg<2, 1>) : Return<2>;
                };
              };
            };
          };
        };

        export default builder as unknown as Root;
      `)
    })
});
